/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import model.Disciplina;

/**
 *
 * @author evert
 */
public class Tela extends javax.swing.JFrame {
    Disciplina[] vet = new Disciplina[20];
    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tfnomedisci = new javax.swing.JTextField();
        tfnomeprof = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        lbn1 = new javax.swing.JLabel();
        lbn2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfn1 = new javax.swing.JTextField();
        tfn2 = new javax.swing.JTextField();
        tfsub = new javax.swing.JTextField();
        tfexame = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        tfpesq = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome da Disciplina:");

        jLabel2.setText("Professor:");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Cadastro de Disciplinas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfnomedisci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnomedisciActionPerformed(evt);
            }
        });

        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbn1.setText("Nota 1:");

        lbn2.setText("Nota 2:");

        jLabel6.setText("Sub:");

        jLabel7.setText("Exame:");

        tfn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfn2ActionPerformed(evt);
            }
        });

        jButton3.setText("Info Requisitos Exame");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tfpesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpesqActionPerformed(evt);
            }
        });
        tfpesq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfpesqKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfpesqKeyTyped(evt);
            }
        });

        jLabel4.setText("Procurar disciplina:");

        txarea.setColumns(20);
        txarea.setRows(5);
        jScrollPane1.setViewportView(txarea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(tfexame, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfnomedisci, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfpesq, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfnomeprof, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbn2)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfn2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbn1)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfn1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfsub, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfnomedisci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfpesq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfnomeprof, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbn1)
                            .addComponent(tfn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbn2))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfsub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel7)
                    .addComponent(tfexame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfnomedisciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnomedisciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnomedisciActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        if (tfnomedisci.getText().equals("") || tfnomeprof.getText().equals("")) {
                throw new ArithmeticException("Campo de texto 'Nome da Disciplina' ou 'Professor' não pode estar vazio");   
            }
        for (int i = 0; i<20;i++){
        if (!(vet[i]==null)){
        if (vet[i].Consulta("nome").equals(tfnomedisci.getText())){
            vet[i]=null;
                vet[i] = new Disciplina(tfnomedisci.getText(), tfnomeprof.getText());  
        
            if (tfn1.getText().trim().equals("")==false){
                vet[i].cadastraN1(Double.parseDouble(tfn1.getText().replace(",", ".")));
            } 
            
             if (tfn2.getText().trim().equals("")==false){
                vet[i].cadastraN2(Double.parseDouble(tfn2.getText().replace(",", ".")));
            }    
             if (tfsub.getText().trim().equals("")==false){
                vet[i].cadastraSub(Double.parseDouble(tfsub.getText().replace(",", ".")));
            } 
             if (tfexame.getText().trim().equals("")==false){
                vet[i].cadastraEx(Double.parseDouble(tfexame.getText().replace(",", ".")));
            } 
        }
        }
        }
          for (int i = 0 ; i<20;i++){ //funciona daqui pra baixo
        if(vet[i]==null){
              boolean autorizado=true;
   
        
            for(int j=i-1;j>=0;j--){
                if (!(vet[j]==null)){
                if (vet[j].Consulta("nome").equals(tfnomedisci.getText())==false){
                    autorizado=true;
                }
                
                else{
                    autorizado=false;
                    j=-1;
                }
                }
            }
            
        if (autorizado){
                 vet[i] = new Disciplina(tfnomedisci.getText(), tfnomeprof.getText());
            if (tfn1.getText().trim().equals("")==false){
                vet[i].cadastraN1(Double.parseDouble(tfn1.getText().replace(",", ".")));
            }    
             if (tfn2.getText().trim().equals("")==false){
                vet[i].cadastraN2(Double.parseDouble(tfn2.getText().replace(",", ".")));
            }    
             if (tfsub.getText().trim().equals("")==false){
                vet[i].cadastraSub(Double.parseDouble(tfsub.getText().replace(",", ".")));
            } 
             if (tfexame.getText().trim().equals("")==false){
                vet[i].cadastraEx(Double.parseDouble(tfexame.getText().replace(",", ".")));
            }
             i=20; 
        }
        }
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if (vet[0]!=null){
        txarea.append("Lista de Disciplinas: \n");
        }
        else {
            txarea.append("Não há disciplinas cadastradas\n\n");
        }
        for ( int i = 0 ; i<20;i++){
            if (vet[i]!=null){
                txarea.append(i+1 + " - " + vet[i].Consulta("nome") + "\n");
                
                }
            }     
        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfn2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        if (!(vet[0]==null)){
        txarea.append("Notas necessárias no exame: \n");   
        for (int i = 0; i<20; i++){
                if (!(vet[i]==null)){
                    txarea.append("Disciplina: "+ vet[i].Consulta("nome") + "\n" 
                            + vet[i].media() + "\n"
                            + "Precisa tirar " + vet[i].faltaexame() + " no exame\n\n");
                }
            }
        }
        else{
            txarea.append("Não há informação para ser listada\n\n");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfpesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpesqActionPerformed
  
        
       // TODO add your handling code here:
    }//GEN-LAST:event_tfpesqActionPerformed

    private void tfpesqKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpesqKeyPressed
  /*if(evt.getKeyCode() == evt.VK_ENTER){
            JOptionPane.showMessageDialog(null, "enter pressionado");
        }*/
  
  if(evt.getKeyCode() == evt.VK_ENTER){  
     for (int i=0;i<20;i++){
       if (!(vet[i]==null)){     
       if (tfpesq.getText().equals((vet[i].Consulta("nome")))){
            
            tfnomedisci.setText(vet[i].Consulta("nome"));
            tfnomeprof.setText(vet[i].Consulta("professor"));
            
            
            if (!(Double.parseDouble(vet[i].Consulta("n1"))>=0 && Double.parseDouble(vet[i].Consulta("n1"))<=10)){
                    tfn1.setText("N/A");
            }
            else{
                tfn1.setText(vet[i].Consulta("n1"));

            }
            if(!(Double.parseDouble(vet[i].Consulta("n2"))>=0 && Double.parseDouble(vet[i].Consulta("n2"))<=10)){
            
             tfn2.setText("N/A");
            }
            else{
               tfn2.setText(vet[i].Consulta("n2"));
            }
            if (!(Double.parseDouble(vet[i].Consulta("sub"))>=0 && Double.parseDouble(vet[i].Consulta("sub"))<=10)){
                tfsub.setText("N/A");
            }
            else{
                tfsub.setText(vet[i].Consulta("sub"));
            }
            if (!(Double.parseDouble(vet[i].Consulta("exame"))>=0 && Double.parseDouble(vet[i].Consulta("exame"))<=10)){
            tfexame.setText("N/A");
            }
            else{
                tfexame.setText(vet[i].Consulta("exame"));
            }
            
             
       }
        }
        
        
        
        }
}
        

        // TODO add your handling code here:
    }//GEN-LAST:event_tfpesqKeyPressed

    private void tfpesqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfpesqKeyTyped
          
        
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_tfpesqKeyTyped

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbn1;
    private javax.swing.JLabel lbn2;
    private javax.swing.JTextField tfexame;
    private javax.swing.JTextField tfn1;
    private javax.swing.JTextField tfn2;
    private javax.swing.JTextField tfnomedisci;
    private javax.swing.JTextField tfnomeprof;
    private javax.swing.JTextField tfpesq;
    private javax.swing.JTextField tfsub;
    private javax.swing.JTextArea txarea;
    // End of variables declaration//GEN-END:variables
}
